### ISSUE TITLE
use `undertaker` insteadof `orchestrator`

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate#1]
- it have better handling
- better structured
- give a good things that orchestrator dont have

and btw, the project looks good :)

**Comment by jonschlinkert** [comment]
yeah we just talked about that. there were thing about undertaker I didn't like, for one it uses common method like `.get()` and `.set()` if I recall, which is going to conflict with any other application that has those methods. 

I'l have to take another look at it.

> and btw, the project looks good :)

thanks!

**Comment by jonschlinkert** [comment]
we're using composer now, which uses bach
