### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by stefanwalther** [generate/generate#11]
Whatever I am doing, I always get the following error message (using node 4.4.5):

```bash
/Users/xxx/.nvm/versions/node/v4.4.5/lib/node_modules/generate/lib/utils.js:31
      .apply(console, [utils.log[color](msg), ...rest]);
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
````

I installed `generate` globally, did the same for `generate-node`, then did a `$ gen node:mit` ...

Any ideas, am I missing something?

Regards
Stefan

**Comment by jonschlinkert** [comment]
you need to update node.js to a more recent version. 5 or greater. It's surprising you're only seeing this error now, since a lot of libs in the dependency tree use es2015 syntax

**Comment by stefanwalther** [comment]
OK; will give it a try ... then you should update the package.json, since it is saying:

```js
"engines": {
    "node": ">=4.0"
  },
```

**Comment by jonschlinkert** [comment]
k, thx

**Comment by jonschlinkert** [comment]
closing, created https://github.com/generate/generate/issues/12
