### ISSUE TITLE
built-in "generators" / commands not work (as expected?)

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate#16]
```
% ❯ gen --version                                                                                          July 09, 02:08:24
[02:08:26] starting generate
Update v0.8.2
```
_(and notice the "Update" instead of "Generate", but nevermind haha - THIS IS THE BIGGEST BUG MAAAN, jk)_

Before few days when i was reviewing the things again there were (if i remember correctly) separate files for the init, help, new and etc, and they were (in `lib/commands/` folder) called "built-in generators" and they looked like any generator which make sense. _(btw, just noticing that `lib/` itself is generator [haha that's freakin' fun ;d] and you started porting commands there? )_

The `new` "generator"/command, works but do not adds the `generator.js` file. Maybe that's because there's no templates dir in this repo (according to [lib/generator.js#L36-L43](https://github.com/generate/generate/blob/master/lib/generator.js#L36-L43)) - if that's the reason, okey, but why it not errors may be the next question.

Nevermind, i'm not rushing you, just digging around as usual in the late night :) In anyway, the work is awesome!

**Comment by jonschlinkert** [comment]
> The new "generator"/command, works but do not adds the generator.js file. Maybe that's because there's no templates dir in this repo

completely forgot to wire that up again, thanks for the reminder. 

> called "built-in generators" and they looked like any generator which make sense

yeah, right now I'm trying to externalize the built-in stuff to external generators, so `gen new` will be powered by a `generate-new` generator. But I forgot to publish it. 

I'm also reworking some of the commands and the help menu to be simpler. thanks for the issue, helps me clarify what needs to be prioritized

> the work is awesome!

thanks!

**Comment by jonschlinkert** [comment]
btw, [these commands](https://github.com/generate/generate/blob/master/lib/commands.js) are where I add new commands while I'm getting one of the apps working. If the command makes sense I will move it into `base-cli-process` for all of the apps
