### ISSUE TITLE
cli: list generators

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate#19]
see https://github.com/generate/generate/issues/18#issue-164653643

**Comment by jonschlinkert** [comment]
![image](https://cloud.githubusercontent.com/assets/383994/16706644/10c29f56-4582-11e6-9405-5b8ee4bbcc16.png)

**Comment by tunnckoCore** [comment]
Starting to think that it's not a good choice `gen` to have commands - or they should not be too much. How `gen list` will differs from `generate-list` on day? Also the `generate-init` is cool name, but it will be forbidden because the command init. Feel the conflicts?

**Comment by jonschlinkert** [comment]
right, they need to be externalized into generators. I mentioned that earlier. 

Eventually, _we won't have any built in tasks or generators_.

**Comment by jonschlinkert** [comment]
oh, however...

> How gen list will differs from generate-list on day?

Once `generate-list` is published, (@doowb might have that), if you installed it globally it would override the built-in `list` command

**Comment by tunnckoCore** [comment]
> it would override the built-in list command

make sense, but then how user will access the real `list` command that list the generators ;d

**Comment by jonschlinkert** [comment]
like this `gen defaults:list` :)

**Comment by jonschlinkert** [comment]
keep in mind that will only happen when you intentionally override the defaults...

**Comment by jonschlinkert** [comment]
oh, and if you don't like doing `$ gen defaults:list`, then do this:

```sh
$ gen foo --macro defaults:list
```

Where `foo` is whatever name you want to save the command as. Then run `$ gen foo`
