### ISSUE TITLE
generator: generate-changelog

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate#20]
Which to follow keep-a-changelog standard would be useful too.

**Comment by jonschlinkert** [comment]
for reference: https://github.com/olivierlacan/keep-a-changelog. that's pretty awesome, I haven't seen it before. 

I can update [helper-changelog](https://github.com/helpers/helper-changelog) to use the `keep-a-changelog` conventions. It's pretty close but I could add the tags for `removed`, `added` etc

**Comment by tunnckoCore** [comment]
> that's pretty awesome

Yea, i'm trying to follow it from 1-2+ years, but don't have so big projects or libs to have need more than the commit msg (with one two words more or some other bullet), it's enough for now, for me.

**Comment by jonschlinkert** [comment]
> it's enough for now, for me.

yeah I'm the same way. I need to get better at changelogs thought.

**Comment by jonschlinkert** [comment]
I was about to close this, I thought I published generate-changelog weeks ago. apparently I didn't push it up! coming soon!

**Comment by jonschlinkert** [comment]
damn, I remember why I didn't https://github.com/lob/generate-changelog. Need to come up with a different name. suggestions?

**Comment by jonschlinkert** [comment]
proposed names:

- `generate-log` (probably my favorite, we can explain that `generate-changelog` was taken ;P)
- `generate-history`
- `generate-changelog2`
- `generate-release-history`
- `generate-change-log`

any others?

**Comment by tunnckoCore** [comment]
Hahaha. Why not try to discuss it with @lob? Then maybe `generate-history`.

**Comment by doowb** [comment]
I like `generate-log` too. Seems to line up with `git log`.

**Comment by jonschlinkert** [comment]
generate-changelog looks like a nice project, and it's well established and well done. I don't want to bother him about something this trivial.

**Comment by jonschlinkert** [comment]
> Seems to line up with git log.

yeah that's what I was thinking. that seems to be a common usage of the term anyway https://en.wikipedia.org/wiki/Changelog

**Comment by jamen** [comment]
I like `generate-history` the most, but `generate-log` is nice too (So I don't tie this up 50/50).

**Comment by tunnckoCore** [comment]
@jamen :+1:

**Comment by jonschlinkert** [comment]
> I like generate-history the most

That was my initial thought, then it occurred to me that users might expect a generator with that name to actually generate a history. But this won't do that. should it? My thinking is that `generate-log` should do just that, generate a "new changelog". Then we can publish `update-log` to actually append history. or `generate-history` to do that. 

sound ok?

**Comment by jonschlinkert** [comment]
ok, I went ahead and published: https://github.com/generate/generate-log. Now that it's published we can discuss what it should do and make any necessary changes
