### ISSUE TITLE
Windows!

### ISSUE THREAD

**Issue by pointnet** [generate/generate#23]
Hello guys,

I can't use generate on windows 8, only `version` work, am I missing something ?

```shell
C:\Users\Aurelien\Documents\GitHub
λ generate cwd
[11:44:26] starting generate
[11:44:26] changing cwd to ~/Documents\GitHub\C.UsersAurelienDocumentsGitHub
[11:44:26] √ running tasks: [ 'cwd' ]
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
```

```shell
C:\Users\Aurelien\Documents\GitHub
λ generate init
[11:56:43] starting generate
[11:56:44] changing cwd to ~/Documents\GitHub\C.UsersAurelienDocumentsGitHub
[11:56:44] √ running tasks: [ 'init' ]
Error: Cannot find generator: "init" in "C:\Users\Aurelien\Documents\GitHub"
```

Versions:
```shell
C:\Users\Aurelien\Documents\GitHub
λ generate version
[11:56:16] starting generate
[11:56:17] changing cwd to ~/Documents\GitHub\C.UsersAurelienDocumentsGitHub
generate v0.8.7

C:\Users\Aurelien\Documents\GitHub
λ node --version
v6.2.2

C:\Users\Aurelien\Documents\GitHub
λ npm --version
3.10.2

C:\Users\Aurelien\Documents\GitHub
λ ver
Microsoft Windows [Version 6.3.9600]
```

**Comment by jonschlinkert** [comment]
I'll look into it today, I have a windows box I usually test things on. thanks for reporting

**Comment by jonschlinkert** [comment]
Actually I just noticed in the first example you're doing `generate cwd`, there is no `cwd` command. Same with `init`. 

Try doing:

```sh
$ npm install --global generate generate-example
```

Then run

```sh
$ gen example
```

**Comment by pointnet** [comment]
it's in the --help
also https://github.com/generate/generate/blob/bff1efc02efe8b5f7f1d2f83407d4a3ba8937f15/docs/installing-the-cli.md#L26
and https://github.com/generate/generate/blob/bff1efc02efe8b5f7f1d2f83407d4a3ba8937f15/support/docs/installing-the-cli.md#L30

I'll try the gen example and keep you posted.

**Comment by pointnet** [comment]
Installing `generate-example` as global works, I can use it but the behavior seems strange, it does not generate the example.txt file at the root folder, is that the behavior expected ?

```shell

C:\Users\Aurelien\Documents\GitHub\test-generate  (test-generate@1.0.0)
λ ls
package.json

C:\Users\Aurelien\Documents\GitHub\test-generate  (test-generate@1.0.0)
λ gen example
[20:48:20] starting generate
[20:48:21] changing cwd to ~/Documents\GitHub\test-generate\C.UsersAurelienDocumentsGitHubtest-generate
[20:48:21] √ running tasks: [ 'example' ]
[20:48:21] starting example
[20:48:21] starting example:default task
[20:48:21] starting example:example task
[20:48:21] finished example:example task 145ms
[20:48:21] finished example:default task 147ms
[20:48:21] finished example √ 152ms

C:\Users\Aurelien\Documents\GitHub\test-generate  (test-generate@1.0.0)
λ ls
C.UsersAurelienDocumentsGitHubtest-generate/  package.json

C:\Users\Aurelien\Documents\GitHub\test-generate  (test-generate@1.0.0)
λ cd C.UsersAurelienDocumentsGitHubtest-generate\

C:\Users\Aurelien\Documents\GitHub\test-generate\C.UsersAurelienDocumentsGitHubtest-generate
λ ls
example.txt
```

**Comment by jonschlinkert** [comment]
> it's in the --help

great thanks. Note that all of those flags are preceded by `--`. Only generator names or tasks can be used as commands (without `--`).

I'm reviewing the docs now to fix mistakes and find potentially confusing language. This is very helpful, thank you.

> it does not generate the example.txt file at the root folder

Hmm, no. It should generate a `example.txt` file at the root. I'll look at it now.

**Comment by pointnet** [comment]
here's the list =>

```shell
\docs\installing-the-cli.md:26:gen init
\support\docs\installing-the-cli.md:30:gen init

\.verb.md:82:$ generate init
\docs\cli\built-in-generators.md:18:$ generate init
\docs\installing-the-cli.md:23:If it's your first time using generate, run `generate init` to set your global defaults.
\support\docs\cli.built-in-generators.md:22:$ generate init
\support\docs\installing-the-cli.md:27:If it's your first time using generate, run `generate init` to set your global defaults.

\.verb.md:103:    --init, -i        Prompts for configuration values and stores the answers
\docs\installing-the-cli.md:47:    --init, -i        Prompts for configuration values and stores the answers
\support\docs\installing-the-cli.md:51:    --init, -i        Prompts for configuration values and stores the answers
\.verb.md:97:    --cwd             Set or display the current working directory
\docs\installing-the-cli.md:41:    --cwd             Set or display the current working directory
\support\docs\installing-the-cli.md:45:    --cwd             Set or display the current working directory
```

**Comment by pointnet** [comment]
Another thing I cannot do on windows but I'm not sure this is the right behavior.
Let's say I install globaly `generate` and I install `generate-example` as a dev dependencie.
Then I cannot run `gen example` which seems weird to me or does generate needs all his generators to be globals too ?

**Comment by pointnet** [comment]
Tests are also crashing on Windows, almost due to paths.
IE:
```shell
1) env createEnv should throw an error when the path is not resolved:
  + expected - actual
  -cannot resolve: 'C:\\Users\\Aurelien\\Documents\\GitHub\\generate\\test\\fixtures\\whatever.js'
  +cannot resolve: 'C:\Users\Aurelien\Documents\GitHub\generate\test\fixtures\whatever.js'
2) helpers integration helper options: should expose global options to helpers::
  + expected - actual
  -a foo\bar\baz b
  +a foo/bar/baz b
```

**Comment by jonschlinkert** [comment]
> does generate needs all generators to be globals too ?

Yes. However, you can run "local" generators the way you want by adding a `generator.js` file in the project with the "sub-generators" you want to run. 

Example:

```js
// --generator.js--
module.exports = function(app) {
  // use any arbitrary name. The name you use will be available
  // by command line. So `$ gen foo` will run this generator
  app.register('foo', require('generate-example'));
};
```

I'm looking into the tests. I ran the tests on windows recently and all passed. I'm not sure what's changed since then

**Comment by jonschlinkert** [comment]
I'm updating everything on windows now to re-run the tests. I'll report back

**Comment by jonschlinkert** [comment]
I found the bug. working on a fix now

**Comment by jonschlinkert** [comment]
Ok, I pushed up a fix. It was something silly, basically the backslashes in cwd were treated as escapes. There are only a few built in commands that are "pre-processed", `cwd` is one of them, so I figured it was something to do with that.

To ensure the necessary files are updated, you should probably do:

```sh
npm cache clean && npm i -g generate generate-example
```

**Comment by pointnet** [comment]
Works like a charm!

**Comment by jonschlinkert** [comment]
great! glad to hear it, thanks for creating the issue, and for working through it with me

**Comment by pointnet** [comment]
It's not that easy to start with your ecosystem when looking for plugins as the doc say that I can also use assemble plugins, as I didn't found a way to find all of them in one place, I made a quick react app plugged onto npmsearch to help find them all.

Maybe this can help someone else or maybe I missed a website somewhere to find them all easily ?

https://pointnet.github.io/react-generate-search/

**Comment by jonschlinkert** [comment]
> It's not that easy to start with your ecosystem when looking for plugins

Agreed! your search page is awesome! 

fwiw we're entirely focused on getting documentation up at the moment - which includes the actual content and websites. that's quite literally all we're working on - we know this is a problem. most of the commit activity you see is related to bugs that crop up, or things we notice while we're working on docs. 

@doowb and I would love to build on what you created, search will be a big part of making it easy to navigate. you just made our lives a lot easier! thanks!

**Comment by pointnet** [comment]
Here's the list I'm using to query npmsearch keywords, please tell me if I'm missing somes:

```shell
'keywords:baseplugin',
'keywords:base-plugin',
'keywords:assembleplugin',
'keywords:assemble-plugin',
'keywords:generateplugin',
'keywords:generate-plugin',
'keywords:generategenerator',
'keywords:generate-generator',
'keywords:templatesplugin',
'keywords:templates-plugin',
'keywords:updateplugin',
'keywords:update-plugin',
'keywords:verbplugin',
'keywords:verb-plugin'
```

I'll work on tools based on `generate` for the react community and it will be a pleasure to help you guys on that search part, I'll publish my source code later on when `verb` and other stuff will be in it ;-).

I'm also thinking of generating react apps via `verb`, do you guys think this could make sense ?

**Comment by jonschlinkert** [comment]
> Here's the list I'm using to query npmsearch keywords,

that looks comprehensive, thanks!

I'm having connection issues but I wanted to comment quickly before I get disconnected again. I'll comment more after I get my connection fixed, maybe @doowb has some thoughts in the meantime. thanks!

**Comment by doowb** [comment]
You can add [update-updater](https://www.npmjs.com/search?q=update-updater).

Since some of the plugins returned for `assemble-plugin` are for `grunt-assemble`, we should get those cleaned up by using a new keyword. Once we do that, we can add the new keyword to the list.

**Comment by jonschlinkert** [comment]
> for grunt-assemble, we should get those cleaned up by using a new keyword

good point. maybe we should do a batch update of the curated plugins to fix the keywords? Or, for now it would probably be a lot easier to just create a whitelist/blacklist to filter assemble plugins. thoughts?
