### ISSUE TITLE
Use XDG base directories for cache/data?

### ISSUE THREAD

**Issue by jamen** [generate/generate#27]
While cleaning up, I see the folder `~/.data-store` being used to store what seems to be just some cache.

Is there a reason `XDG_CACHE_HOME` or `XDG_USER_DATA` or their defaults (`~/.cache` and `~/.local/share`) are not being used here?  I have a lot of folders in my home directory I wish weren't there.

I can try and pull request this (maybe on `data-store` if needed, and then here) if it is an idea that sounds good to add.  Maybe also with some Windows equivalents.

**Comment by jonschlinkert** [comment]
yeah I'm definitely open to it! Honestly I haven't given that as much thought as I should, I've been focused on general usability. I just mentioned to @doowb recently that the storage directories need to be re-thought, so this is timely.

**Comment by tunnckoCore** [comment]
>  have a lot of folders in my home directory I wish weren't there.

:+1: Yea, definitely. Same here.

But maybe `~/.config` would make more sense, but in any case it's better to not be in home.

**Comment by jleeto** [comment]
I concur with @doowb --  `~/.config` would be more efficient and makes more sense.

**Comment by jonschlinkert** [comment]
AFAIK this wasn't implemented, but I want to make sure it is.

**Comment by jamen** [comment]
See https://github.com/jonschlinkert/data-store/pull/8
