### ISSUE TITLE
bug: generator.js should be resolved directly

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate#29]
When a globally or locally installed npm package has a `generator.js` file, we should use that directly and not try to use it through `index.js`.

**Comment by jamen** [comment]
Why is that?  Just kind of curious.  Can you not require the modules directly?

**Comment by jamen** [comment]
But for people who make generators, doesn't following the package.json `"main"` behavior seem appropriate?  Could be done with something like [`requireg`](https://www.npmjs.com/package/requireg) perhaps.

**Comment by jonschlinkert** [comment]
> doesn't following the package.json "main" behavior seem appropriate

yeah, that's what we do now. Maybe this isn't really worth doing, but I was looking at that other `generate-changelog` project and thinking that they could easily drop a `generator.js` file in the project to turn the existing code into generator, while staying completely backwards compatible. But... as it is currently generate would try to resolve `index.js` "just because". 

what are your thoughts? I'm going back and forth on it

**Comment by jamen** [comment]
Hmm, what is the usecase there?  Shouldn't generators usually be standalone modules?  Adding a `generator.js` to a project that isn't a generator seems less beneficial to me than following with `"main"`.  

I also feel like if `"main"` had no functionality inside the module, people would get confused on how the entry works, unless it is explicitly noted at the top of the docs or something, but even then still probably would be confusion.

**Comment by jamen** [comment]
Haha, probably would have made a nice and easy pull request to have `generate-changelog` though.

**Comment by jonschlinkert** [comment]
lol yeah, but you are indeed correct. I think we can leave it as-is. good feedback thanks
