### ISSUE TITLE
Finally, how can customize the templates?

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate#32]
I'm totally lost already. :D The docs on the `support/templates/customization` only says _"if you wanna cutomize more that single file, use scaffolds"_ where "scaffolds" is link to `support/templates/`. 

Anyway. What you use currently with latest updates? How should override templates used by `generate-project` for example? Should I set them in `~/generate/project/templates` or `~/generate/templates`, or to `~/templates` how it is said on `generate-project`s `docs` folder (i believe? it was before few minutes but..)?

I wanna start update everything this night and wanna start using `verb`, `generate` and `update` completely. 'Cuz I need tons of updates for last months and it is complete hell already, because I dont have this time these months. I have much things to push, and start working on and am exited to do it; and i dont have the time and willing to deal with such stuff. And actually that's the reason why I didn't have contribs recently - from 4900 to 3200... Nevermind.

You know, i'm The Unlucky guy :D that always have some fails using your libs ahahha, jk (some sort).

**Comment by jonschlinkert** [comment]
I don't even know what this issue is about. It sounds like you found a broken link in the docs, but you didn't even link to it, which creates even more work just to ask for it. Feel free to create an issue about a specific thing without ranting, or just don't use generate, verb or assemble until the docs for all of them are complete. We don't have the bandwidth to write documentation as issue responses.

**Comment by tunnckoCore** [comment]
> I don't even know what this issue is about.

It's strictly about how to customize the templates of no matter what generator i use.

> How should override templates used by `generate-project` for example? Should I set them in ~/generate/project/templates or ~/generate/templates, or to ~/templates how it is said on `generate-project`s `docs` folder (i believe? it was before few minutes but..)?

**Comment by tunnckoCore** [comment]
For the last 2-3 moths I've seen all of these directories in the couple of readmes and in the docs, so finally, i don't know which one to use.

**Comment by jonschlinkert** [comment]
Then please just focus the issue on what it is, a simple broken link in unpublished, draft documentation. 

The folder for custom templates is `~/templates`.  

if you want to see the code, 100% of the logic for this feature is [right here](https://github.com/generate/generate/blob/master/lib/mixins.js#L58-L73).

**Comment by doowb** [comment]
@tunnckoCore you pointed to a support template that is used when building docs and it has the `draft` flag set. Those aren't completed docs and the feature might not exist.

>  couple of readmes and in the docs

If you see information that is incorrect in the readmes, please open an issue that points to that readme. I only recall discussions in issues about how to configure customizable templates, the only one that has been implemented is `~/templates`.

**Comment by jonschlinkert** [comment]
ooooohhhh, see what you did? You know you're in deep doodoo when @doowb steps in. no more shenanigans, no more tomfoolery, no more ballyhoo. 

Sincerely though, my apologies. Here is [an updated link](https://www.youtube.com/watch?v=NgWn7zbgxZ4) with the docs for customizing templates.

**Comment by doowb** [comment]
lol, don't... click... that... link

**Comment by doowb** [comment]
Unless you want a good laugh

**Comment by jonschlinkert** [comment]
Not sure what @doowb's referring to.

**Comment by jonschlinkert** [comment]
I remember when someone rick-rolled me with that a few years ago. but I forgot how bad it was so I remove it lol. it's just weird
