### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by connorhartley** [generate/generate#36]
I downloaded the latest version of generate as well as generate-package, generate-license and a few others, but when I run package and license they both error.

Package error: https://gist.github.com/connorhartley/a15cd6392e77d5fed34a9bb87ad6364b
License error: https://gist.github.com/connorhartley/5ecb0d5d53b5acee201fac02646a7f8a

Version details:
Windows 10
node v6.5.0
npm v3.10.6
generate v0.11.2

**Comment by jonschlinkert** [comment]
Hmm, at first I thought I knew the cause, but after reviewing the errors I'm not sure. I'll look into it. @doowb any thoughts?

thanks for reporting. 

(on the off-chance that it's related to what I was initially thinking... the following is what my response would have been)

There is a known bug causing this, it's a pretty easy fix that in reality will take 5 min, but I want to shift some code around to prevent similar errors from happening. 

Here is what's happening and what I'm doing about it.

- There are just a handful of fields that we try to pre-populate  for you, like license - if available (using user environment, package.json, etc). 
- these pre-populated fields should only be used as "hints" when you run generate. However...
- I introduced a regression in a recent release. To explain, there are two places that come to mind where `license` is used differently. In package.json the `license` field expects a valid SPDX license as its value, but in the readme templates (in the generators I created - this is where my lapse of judgement caused the error) the `license` template variable is used to populate the license "statement". This value is overwriting the value from prompts. That shouldn't happen. Again, it was human error (mine). 

Sorry about this. I'll get it fixed and update this when it's done.
