### ISSUE TITLE
generate-example not working as intended

### ISSUE THREAD

**Issue by JelaniThompson** [generate/generate#37]
Hi there!

I've been recommended by my friend Jamen Marzonie to help contribute to this project. I started tinkering with it and came across an issue right off the bat. 

I'm tried running `npm install --global generate-example` followed by `gen example` and got the following in return:
```
[21:27:15] starting generate
[21:27:15] ✔ running tasks: [ 'example' ]
[21:27:15] starting example
[21:27:15] starting example:default task
[21:27:15] starting example:example task
[21:27:16] finished example:example task 182ms
[21:27:16] finished example:default task 184ms
[21:27:16] finished example ✔ 195ms
```
Although it says the building the example was successful, when I check `example.txt`, the contents `foo` aren't added. How can I go about fixing this?

**Comment by jonschlinkert** [comment]
Hmm, strange. The [template for example.txt is here](https://github.com/generate/generate-example/blob/master/templates/example.txt). I'll look into it.  In the meantime, would you mind if we move this issue over to https://github.com/generate/generate-example? I can or you can, thanks!
