### ISSUE TITLE
bug: the reverse of inverse flags should be set on options

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate#41]
When `--nofoo` is set, it adds `nofoo: true` to the options.  `foo: false` should also be added to the options. I thought yargs-parser did this but I might need to set an option for it. I think the best solution is to ensure this is done regardless of the args parser used.

**Comment by tunnckoCore** [comment]
it's seems you're wrong. one thing is `--nofoo` totally another is `--no-foo` i believe? and yargs/minimist does it? hm

**Comment by tunnckoCore** [comment]
> Are you suggesting we also support --no-foo?

If it's not supported currently, it make sense to be supported. And it's more real and natural for me than `--nofoo`. :)

**Comment by jonschlinkert** [comment]
ok, that makes sense
