### ISSUE TITLE
Using generate inside of modules?

### ISSUE THREAD

**Issue by jamen** [generate/generate#42]
I'm collaborating on this project called `cordlr` and I just thought of an interesting idea.

We are making this `cordlr setup` command so it prompts the user for data and then creates some files and possibly also would install dependencies.

I was thinking about how it would be cool if there was a minimal version of `generate` I could use as a dependency just to make those mechanisms easier, for prompting, creating of the files, install dependencies, and whatever else.

I would normally suggest people to just use `generate` instead, but this has audience for not just programmers and idk if everyone would want to jump around to different tools.  So, it would be cool to use this as a library.

The command line will also do other things that I think generate could be useful for. We might also use `base` in other areas for our plugins too, so it would look normal.

**Comment by jamen** [comment]
For the record, the command line will also do other things that I think generate could be useful for.

We might also use `node-base` in other areas too, so it would just look more normal.

**Comment by jamen** [comment]
Hmm, I guess it actually doesn't include that much.  maybe i could try this already.

**Comment by jonschlinkert** [comment]
absolutely. you can completely customize the experience

> minimal version of generate

I can think of a couple different approaches, depending on whether or not you need to run globally installed generators by command line (e.g. using a namespace, similar to `generate-*`). 

If you list a few high level requirements for your app I'd be happy to give suggestions on approach.

**Comment by jamen** [comment]
I was thinking of just using `generate` and generators as dependencies for the functionality they have.  I could just run them through my own simpler scripts that wouldn't need the global installing and namespacing things.

Like, for example `cordlr setup` would:
 - Prompt the user `token`, `prefix`, and `plugins`.
 - Create a `.cordlrrc` file with the prompt results.
 - Install the `plugins` with npm and save them.

Then there is also `cordlr install <...plugins>` which would npm install and save, and also add to the `.cordlrrc` `plugins` field.

I was thinking I could use generate APIs to make it easier, but I wouldn't need a lot of the CLI dependencies I see installed with it.

**Comment by jonschlinkert** [comment]
makes sense, have you seen [base-app](https://github.com/node-base/base-app)? Might be a good choice if you don't need to create template collections or render templates. Or even consider using `assemble-core` if you need middleware and collections. Most generate plugins (generators) should work with `base-app` or `assemble-core`. 

or just look at how those are done and create your own. Here is an example:

```js

var task = require('base-task');
var option = require('base-option');
var plugins = require('base-plugins');
var generators = require('base-generators');
var Base = require('base');

function App(options) {
  Base.call(this, null, options);
  this.isApp = true; //<= used to ensure only "app-level" plugins are used
  this.is('cordlr');
  this.use(plugins());
  this.use(generators());
  this.use(option());
  this.use(task());
}

Base.extend(App);

/**
 * Expose `App`
 */


module.exports = App;
```


<br>

**Example usage**

```js
var app = new App();

app.task('default', function(cb) {
  console.log(app.namespace, 'task >', this.name);
  cb();
});

app.generator('foo', function(foo) {
  this.task('default', function(cb) {
    console.log(foo.namespace, 'task >', this.name);

    // run the `default` task on `app`
    app.build('default', cb);
  });

  this.generator('bar', function(bar) {
    this.task('default', function(cb) {
      console.log(bar.namespace, 'task >', this.name);

      // run the `default` task on `app`
      foo.build('default', cb);
    });
  });
});

app.generate('foo.bar:default', function(err) {
  if (err) console.log(err);
});
```

Not sure if you're familiar with how sub-generators work, but if you play around with this example you'll see how they can be nested.

**Comment by jonschlinkert** [comment]
btw, the `.namespace` property shows the generator's name in context to the generator hierarchy. So the innermost generator's namespace in the example is `app.foo.bar`

**Comment by jamen** [comment]
Interesting.  I had not seen all the other `base` plugins before.   That code is pretty easy to understand, nice work :+1:.

I think I'll try using some custom app with `base` instead of `base-app` and see what I can make with it.

**Comment by jonschlinkert** [comment]
> I think I'll try using some custom app with base

great! let us know if we can help
