### ISSUE TITLE
fails when git repository does not exist

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate#47]
related to https://github.com/generate/generate/issues/30#issuecomment-313271546 

@seanc can you provide some details on your setup? OS, node.js version, etc?

**Comment by rbecheras** [comment]
I can't reproduce this bug using

- Ubuntu Gnome 17.10
- Node LTS Carbon v8.9.4
- NPM v5.6.0
- generate v0.14.0
- generate-project v1.0.0
- generate-license v1.0.0

**Comment by rbecheras** [comment]
[![asciicast](https://asciinema.org/a/POn71LncqxWcqgmvxol5nOlt6.png)](https://asciinema.org/a/POn71LncqxWcqgmvxol5nOlt6)

**Comment by jonschlinkert** [comment]
closing, due to lack of reply and since we aren't able to reproduce.
