### ISSUE TITLE
Can't run the generator that's installed globally

### ISSUE THREAD

**Issue by veljkoz** [generate/generate#51]
I can't run a globally installed generator:

```
npm install -g generate generate-gitignore
gen gitignore
```

Error reported suggests the generator can't be found:

```
C:\temp\> gen gitignore
[13:56:05] starting generate
[13:56:06] √ running tasks: [ 'gitignore' ]
Error: Cannot find generator: "gitignore" in "C:\temp"
. . .
```

Note that when `generate:gitignore` is installed locally it works, so I'm guessing the problem is on the "generate" side.

gen -V
generate v0.14.0

npm -v
5.6.0

node -v
v8.11.1

**Comment by jonschlinkert** [comment]
Sounds like a bug. I'm not sure why the CLI is looking for a local generator and not resolving the global one. Do you use `nvm` or anything like that? Anything else about your config that might help debug?

**Comment by veljkoz** [comment]
Yes, good guess - I do use nvm for Windows, v1.1.5... (it's so behind the scenes, that I almost forget I have it).

**Comment by rbecheras** [comment]
@veljkoz did you find the solution to your problem ?

**Comment by veljkoz** [comment]
no, still doesn't work... I had to add it locally into devDependencies and generated it from there...

**Comment by tunnckoCore** [comment]
i'm using nvm for years, so maybe that isnt the problem. or it may be something wrong but only on windows

**Comment by tunnckoCore** [comment]
can you give some paths - to global modules and etc. Or try what `global-modules` outputs and `global-prefix`

**Comment by veljkoz** [comment]
```
var gm = require('global-modules');
console.log(gm);
```
Output: 
`C:\Users\_myusername_\AppData\Roaming\npm\node_modules`

----
```
var gp = require('global-prefix');
console.log(gp);
```
Output:
`C:\Users\myusername\AppData\Roaming\npm`

**Comment by doowb** [comment]
@veljkoz will you also show the output of this command: `npm root --global`

**Comment by tunnckoCore** [comment]
And `npm bin --global` too?

**Comment by veljkoz** [comment]
`npm bin --global:`
> C:\Program Files\nodejs

`npm root --global`
> C:\Program Files\nodejs\node_modules

**Comment by tunnckoCore** [comment]
Yea. Seems like a problem. Can you check in which folder is the generate-gitignore and generate? Seems like there are two global node modules folders.

In roaming/npm/node_modules or in the programFiles/nodejs/node_modules?

**Comment by veljkoz** [comment]
Hm, interestingly, the roaming/npm folder doesn't exist - the nvm does: `myuser\Roaming\nvm\v8.11.1\node_modules`, and there I can find both `generate` and `generate-gitignore`. I'm guessing the nvm manages this per-version loaded.

As for the `C:\Program Files\nodejs\node_modules`, it also has both `generate` and `generate-gitignore`.

**Comment by veljkoz** [comment]
Note: I just tried setting the environment variable `NODE_PATH` to `C:\Program Files\nodejs\node_modules` - now I can require global packages in node, but the result is still the same (`gen gitignore` still looks only local generators)

**Comment by doowb** [comment]
@veljkoz thanks for the additional information. As @olstenlarck pointed out, we use `global-prefix` and `global-modules` to try to find where the global `node_modules` folder is. This logic is based on how `npm` does it so it's usually correct. `nvm` may or may not be doing something different which is causing `global-prefix` to fallback to a default for windows based on the `APPDATA` environment variable.

I'll have to look into it more on windows to try to figure out if there's a way we can figure it out, but for now, you can set the `PREFIX` environment variable to the location of your node executable that you got from running `npm bin --global` (`C:\Program Files\nodejs`). This will tell `global-prefix` to use that.

edit: I tried this on Windows 10 and it found the same one as `npm bin --global`:

```cmd
> set PREFIX="C:\Program Files\nodejs"
> node -e "console.log(require('global-prefix'));"
```

**Comment by tunnckoCore** [comment]
Hmm... exactly. I cant remember but I will try later today what global-modules gives me. I suppose that it does not respect NVM.

Try to add NVM_DIR too, or what it was. hm.

**Comment by veljkoz** [comment]
Hm, just looking at the global-prefix... [this line](https://github.com/jonschlinkert/global-prefix/blob/49684bdf64fd6e5f11dc7caac8c6eb9abfd376b9/index.js#L57) seems to be the culprit. The `path.dirname(process.execPath)` would've been enough to get the correct node path... does anyone know why is this `APPDATA` assumed to be the correct path? (maybe I should move this question to that gitrepo?)

**Comment by doowb** [comment]
[This PR](https://github.com/jonschlinkert/global-prefix/pull/5) is the one that added `APPDATA` and has an explanation for why it would be used.

> maybe I should move this question to that gitrepo?

If you have any additional issues (if setting `PREFIX`) doesn't work for you, then please open an issue in the `global-prefix` repo. I'm going to close this here.

**Comment by tunnckoCore** [comment]
There should have a fix to check for prefix added in .npmrc, and fix for nvm based environment too.

I will check what's happening on linux, so we won't break smth.

**Comment by tunnckoCore** [comment]
Yup. Here, in linux, `global-prefix` correctly resolves to the NVM path. I think it should be that way on Windows too.

```bash
~/tunnckoCore
❯ node -e "console.log(require('global-prefix'));"
/home/charlike/.nvm/versions/node/v10.3.0

```

**Comment by tunnckoCore** [comment]
I think that we can use `$NVM_BIN` and get double `path.dirname` on it, instead of executing `nvm which current` (which was one of my suggestions back in the past, i believe). And make that check, just after the `process.env.PREFIX` check.

@veljkoz can you confirm that you have that env on Windows?

**Comment by veljkoz** [comment]
Sorry to dissapoint, for Windows nvm there's only these two :

> NVM_HOME=C:\Users\myusername\AppData\Roaming\nvm
> NVM_SYMLINK=C:\Program Files\nodejs

The first one has subfolders for every node version installed (e.g. v8.11.1, v10.1.0, etc.). The second one has the node itself along with the node_modules (being it's a symlink it's actually pointing to one of the subfolders of nvm).

**Comment by tunnckoCore** [comment]
Haha, thanks, good to know. And still we can check both of them. It won't be a problem for us, but it's interesting why NVM did it that way.. most inconsistencies and problems between OSes are coming from tools authors, which does some weird things like that. :D 

Anyway, i have some ideas.

**Comment by veljkoz** [comment]
Maybe we should move the discussion [here](https://github.com/jonschlinkert/global-prefix/issues/21), to have everything in one place.
